version: '3'

services:
  redis:
    image: redis:5.0.1-alpine
    ports:
      - "6379:6379"

  publisher:
    build:
      context: .
      args:
          - command=publisher
    ports:
      - "8808:8808"
    links:
      - redis:redis
    command: ./publisher

  consumer:
    build:
      context: .
      args:
          - command=consumer
    links:
      - redis:redis
    command: ./consumer
